---

app:
  logging:
    level: 'DEBUG'
    msg_format: '%(asctime)s.%(msecs)03d [%(levelname)-8s]: %(message)s'
    date_format: '%Y-%m-%d %H:%M:%S'
    sinks:
      stdout: True
      file: null
      # Example for setting logger up to log into file
      # file
        # filename: 'minesweeper.log'
        # max_size: 20971520 # 20 MB
        # backup_count: 5
